{
    "error": {
        "http_code": 400,
        "fields": {
            "lunno": [
                "LUN with ID \"1\" already exists"
            ]
        },
        "traceback": [
            "Traceback (most recent call last):\n",
            "  File \"/usr/libexec/vstorage-ui-backend/venv/lib64/python3.4/site-packages/vstorage_ui_backend-1.3.185-py3.4.egg/backend/presentation/decorators.py\", line 28, in wrapper\n    return func(*args, **kwargs)\n",
            "  File \"/usr/libexec/vstorage-ui-backend/venv/lib64/python3.4/site-packages/vstorage_ui_backend-1.3.185-py3.4.egg/backend/logg.py\", line 127, in wrapper\n    return func(*args, **kwargs)\n",
            "  File \"/usr/libexec/vstorage-ui-backend/venv/lib64/python3.4/site-packages/vstorage_ui_backend-1.3.185-py3.4.egg/backend/presentation/iscsi/endpoints.py\", line 270, in post\n    lun = IscsiPresentation.add_lun(cluster_id, target_iqn, **data)\n",
            "  File \"/usr/libexec/vstorage-ui-backend/venv/lib64/python3.4/site-packages/vstorage_ui_backend-1.3.185-py3.4.egg/backend/business/models/iscsi/presentation.py\", line 1340, in add_lun\n    cluster_id, target_iqn, lunno, size, description, tier, redundancy, failure_domain,\n",
            "  File \"/usr/libexec/vstorage-ui-backend/venv/lib64/python3.4/site-packages/vstorage_ui_backend-1.3.185-py3.4.egg/backend/business/models/iscsi/presentation.py\", line 1328, in _validate_create_lun_params\n    raise FieldsValidationError(errors)\n",
            "backend.business.models.exceptions.FieldsValidationError: {'lunno': ['LUN with ID \"1\" already exists']}\n"
        ],
        "subsytem": "presentation",
        "errors": null
    },
    "message": "Bad Request (Deprecated field)"
}